ltslam:

  sessions_dir: "/data/output/sessions/"   # end with /

  central_sess_name: "01"                  # first half of the run
  query_sess_name: "02"                    # second half, which retraces it

  save_directory: "/data/output/sessions/LT_result/"   # end with /

  is_display_debug_msgs: false

  loopFitnessScoreThreshold: 0.7

  kNumSCLoopsUpperBound: 1000
  kNumRSLoopsUpperBound: 0

  numberOfCores: 16
